# Non-secret defaults for env:prod
WL_NAME: Noma
URL_PREFIX: noma_prod
BASE_URL: https://u8za3vvgbb.execute-api.us-east-1.amazonaws.com/noma_prod
DOC_BASE_URL: https://u8za3vvgbb.execute-api.us-east-1.amazonaws.com/noma_prod
FE_BASE_URL: https://www.travelwithnoma.com
APP_FE_BASE_URL: https://www.travelwithnoma.com
API_GATEWAY_ARN: arn:aws:execute-api:us-east-1:158711196499:u8za3vvgbb
SYS_ENV: noma_prod
AGENT_LANGUAGE: en
NOMA_ROLE_ENFORCEMENT: "on"
DYNAMODB_ENTITY_TABLE: noma-prod_entities
DYNAMODB_BLUEPRINT_TABLE: noma-prod_blueprints
DYNAMODB_RINGDATA_TABLE: noma-prod_data
DYNAMODB_REL_TABLE: noma-prod_rel
DYNAMODB_CHAT_TABLE: noma-prod_chat
COGNITO_REGION: us-east-1
COGNITO_USERPOOL_ID: us-east-1_yydZGkq4N
COGNITO_APP_CLIENT_ID: ede7jbk4ru8mdhomrjiie5c5d
COGNITO_CHECK_TOKEN_EXPIRATION: "True"
PREVIEW_LAYER: "2"
S3_BUCKET_NAME: noma-prod-44841892
WEBSOCKET_CONNECTIONS: https://3vdnaldxj0.execute-api.us-east-1.amazonaws.com/production
ALLOW_DEV_ORIGINS: "false"
CORS_ALLOWED_ORIGINS: https://app.travelwithnoma.com,https://www.travelwithnoma.com,https://travelwithnoma.com
INVITE_FROM: Noma <noreply@travelwithnoma.com>
SES_INVITE_SENDER: noreply@travelwithnoma.com
NEXT_PUBLIC_MS_REDIRECT_URI: https://app.travelwithnoma.com/dashboard/settings/calendar/callback
VITE_EXTENSIONS: schd,data,backend
VITE_WL_LOGO: /small_logo.jpg
VITE_WL_LOGIN: /large_logo.jpg
VITE_DEV_MODE: "false"
