"""Write generated env files for backend, console, and NOMA."""

from __future__ import annotations

import json
import re
from pathlib import Path

BACKEND_KEYS_ORDER = [
    "WL_NAME",
    "BASE_URL",
    "FE_BASE_URL",
    "APP_FE_BASE_URL",
    "DOC_BASE_URL",
    "AWS_REGION",
    "API_GATEWAY_ARN",
    "ROLE_ARN",
    "SYS_ENV",
    "URL_PREFIX",
    "DYNAMODB_ENTITY_TABLE",
    "DYNAMODB_BLUEPRINT_TABLE",
    "DYNAMODB_RINGDATA_TABLE",
    "DYNAMODB_REL_TABLE",
    "DYNAMODB_CHAT_TABLE",
    "CSRF_SESSION_KEY",
    "SECRET_KEY",
    "COGNITO_REGION",
    "COGNITO_USERPOOL_ID",
    "COGNITO_APP_CLIENT_ID",
    "COGNITO_CHECK_TOKEN_EXPIRATION",
    "PREVIEW_LAYER",
    "S3_BUCKET_NAME",
    "OPENAI_API_KEY",
    "RESEND_API_KEY",
    "WEBSOCKET_CONNECTIONS",
    "ALLOW_DEV_ORIGINS",
    "INVITE_FROM",
    "SES_INVITE_SENDER",
    "NOMA_ROLE_ENFORCEMENT",
    "AGENT_LANGUAGE",
    "CORS_ALLOWED_ORIGINS",
    "NEXT_PUBLIC_MS_TENANT_ID",
    "NEXT_PUBLIC_MS_CLIENT_ID",
    "NEXT_PUBLIC_MS_CLIENT_SECRET",
    "NEXT_PUBLIC_MS_REDIRECT_URI",
    "TOKENS_KMS_KEY_ID",
]

NOMA_KEYS = [
    "NEXT_PUBLIC_AWS_USER_POOL_ID",
    "NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID",
    "NEXT_PUBLIC_API_BASE_URL",
    "NEXT_PUBLIC_VITE_API_URL",
    "NEXT_PUBLIC_CHAT_WS",
    "NEXT_PUBLIC_PORTFOLIO_ID",
    "NEXT_PUBLIC_ORG_ID",
    "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY",
    "NEXT_PUBLIC_CHECKOUT_TAB_DISABLED",
    "NEXT_PUBLIC_SIGNUP_POLICY",
    "NEXT_PUBLIC_LOG_LEVEL",
    "RESEND_API_KEY",
    "S3_BUCKET_NAME",
]

CONSOLE_KEYS = [
    "VITE_API_URL",
    "VITE_API_PROXY_TARGET",
    "VITE_WEBSOCKET_URL",
    "VITE_COGNITO_REGION",
    "VITE_COGNITO_USERPOOL_ID",
    "VITE_COGNITO_APP_CLIENT_ID",
    "VITE_WL_LOGO",
    "VITE_WL_LOGIN",
    "VITE_EXTENSIONS",
    "VITE_DEV_MODE",
    "VITE_CROSS_ORG",
]


def _py_literal(value: str) -> str:
    if value.lower() in ("true", "false"):
        return value.capitalize()
    if re.fullmatch(r"-?\d+", value):
        return value
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def write_env_config(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Generated by noma run — do not edit manually",
        "",
    ]
    seen = set()
    for key in BACKEND_KEYS_ORDER:
        if key in values and values[key]:
            lines.append(f"{key} = {_py_literal(values[key])}")
            seen.add(key)
    for key in sorted(values):
        if key.startswith("_") or key in seen:
            continue
        if key.startswith(("NEXT_PUBLIC_", "VITE_")):
            continue
        if values[key]:
            lines.append(f"{key} = {_py_literal(values[key])}")
    if "AWS_REGION" not in values and values.get("COGNITO_REGION"):
        lines.append(f"AWS_REGION = {_py_literal(values['COGNITO_REGION'])}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_dotenv(path: Path, values: dict[str, str], keys: list[str]) -> None:
    lines = ["# Generated by noma run — do not edit manually", ""]
    seen: set[str] = set()
    for key in keys:
        if key in values and values[key] != "":
            lines.append(f"{key}={values[key]}")
            seen.add(key)
    for key in sorted(values):
        if key in seen or not key.startswith(("NEXT_PUBLIC_", "VITE_", "RESEND_", "S3_")):
            continue
        if values[key] != "":
            lines.append(f"{key}={values[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_env_development(path: Path, values: dict[str, str]) -> None:
    lines = ["# Generated by noma run — do not edit manually", ""]
    for key in sorted(values):
        if not values[key]:
            continue
        if key.startswith(("NEXT_PUBLIC_", "VITE_")) or key in (
            "AWS_PROFILE",
            "AWS_DEFAULT_REGION",
        ):
            val = values[key]
            if " " in val or "#" in val:
                val = f"'{val}'"
            lines.append(f"{key}={val}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def backup_if_exists(path: Path) -> None:
    if path.exists():
        backup = path.with_suffix(path.suffix + ".bak")
        if not backup.exists():
            backup.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")


def write_app_files(
    apps: set[str],
    *,
    backend_config: Path,
    backend_env: Path,
    console_env: Path,
    noma_env: Path,
    merged: dict[str, str],
) -> list[Path]:
    written: list[Path] = []
    if "backend" in apps:
        backup_if_exists(backend_config)
        backup_if_exists(backend_env)
        write_env_config(backend_config, merged)
        write_env_development(backend_env, merged)
        written.extend([backend_config, backend_env])
    if "console" in apps:
        backup_if_exists(console_env)
        write_dotenv(console_env, merged, CONSOLE_KEYS)
        written.append(console_env)
    if "noma" in apps:
        backup_if_exists(noma_env)
        write_dotenv(noma_env, merged, NOMA_KEYS)
        written.append(noma_env)
    return written
